### ISSUE TITLE
Protocol Oriented Programming

### ISSUE THREAD

**Issue by cojoj** [czechboy0/XcodeServerSDK#4]
As you know, Apple has presented new way of programming - which will make Crusty happy.

I know it's all about personal taste... But I really like the idea and I think it can release the great power of Swift. 

This whole `XcodeServerEntity`-subclass model in existing SDK is a great candidate to redesign it with **Protocol Oriented Programming**. This will allow to drop this big inheritance tree and implement only necessary stuff. What's more it can allow to replace `class`es with `struct`s which will also have a great impact on performance.

@czechboy0 what do you think?

**Comment by czechboy0** [comment]
The reason why everything inherits from `XcodeServerEntity` is because its `init(json: NSDictionary)` constructor parses out common fields like `id`, `rev` and `tinyID`. Protocols wouldn't allow for that unfortunately, but overall I agree with you that we should be aiming for a protocol-based approach wherever possible.

**Comment by cojoj** [comment]
Old protocols wouldn't but the new ones? I mean, now we can create `extensions` with default implementation - this should be a game changer.

**Comment by czechboy0** [comment]
Sure, but the way the objects are now parsed is that the constructor takes a JSON object, pulls out the fields relevant to it and then calls super with the same objects, which does the same thing... until it reaches the `XcodeServerEntity`, which pulls out the above mentioned fields.

Protocol extensions enable you to only provide a default implementation for all objects conforming to a certain protocol, but AFAIK they don't support inheritance, which is exactly this case.

**Comment by cojoj** [comment]
Sure, with the current architecture of project it's impossible but I was rather thinking about deeper refactoring and dropping this verbose `XcodeServerEntity` inheritance thing. I'd probably do things similar to you but something (maybe a little Crusty in my head) is telling me that it can be resolved with different approach.

I will rethink this and If I come with any kind of solution or idea I will bring it to you! 😉

**Comment by czechboy0** [comment]
Yeah do, thanks!

**Comment by cojoj** [comment]
I've came to [this](http://chris.eidhof.nl/posts/swift-mirrors-and-json.html) little article today and I wonder maybe this will be a good approach?

**Comment by czechboy0** [comment]
Interesting, Chris mentions the library called [`JSONCodable`](https://github.com/matthewcheok/JSONCodable), which I took a look at. Looks very useful for parsing and generating JSON into structs.

There is a couple of reasons why I don't think it would be of much benefit here, mostly because we give different names to properties and to the keys in the JSON. Plus the parsing pattern is very similar to what we're using already, with the exception that we use inheritance to parse the objects, because that's how they are treated by Xcode Server (everything has an `_id` and a `_rev`).

Let's open this if we come up with more actionable ideas.
