### ISSUE TITLE
Using third-party libraries

### ISSUE THREAD

**Issue by cojoj** [czechboy0/XcodeServerSDK#5]
@czechboy0 I cleary see that you're trying to do everything using built-in tools. Are there any specific arguments why? 

I'm now struggling with Swift 2.0 conversion and the most **problematic** classes are eg. `JSON`.

Why doing it manually while we have some great tools like [Argo](https://github.com/thoughtbot/Argo)?

**Comment by czechboy0** [comment]
I'm not fundamentally against using 3rd party tools, I just need to see a significant benefit before I bring something in. Right now there is no dependency in Buildasaur and in XcodeServerSDK. Adding a Podfile and adding that extra step must be then justified before I'm happy to do it.

Argo looks interesting and maybe I'll use it in the future, but for now the couple of convenience functions I wrote for the JSON parsing do the job just as well.

**Comment by czechboy0** [comment]
What issues specifically are you seeing with the JSON parsing classes?

**Comment by cojoj** [comment]
Nah, it's not an issue - it's working and it's fine. It's more like I like using third party libraries (good ones) to focus on what's important for the thing I'm building with my team - in this case it's **XcodeServerSDK**.

I just think that JSON handling is a concern of something totally different but I know if we get into trouble with this we can always add third party integration.

On the other hand, there are other great tools like [Quick](https://github.com/Quick/Quick) or [Alamofire](https://github.com/Alamofire/Alamofire) which at some point may become useful or may not...

**Comment by czechboy0** [comment]
Yeah you're right that we should be focusing on the stuff that makes this project unique. I just try to strike the balance between creating a Frankenstein project of having a dependency for everything and doing everything myself. I guess so far I've been on the far side of the spectrum, but it was mostly because it wasn't that much work to do it myself and I preferred to learn how to do it in Swift. I am not saying we might not move to dedicated frameworks in the future, but I feel like it has to be justified with enough benefit.

**Comment by czechboy0** [comment]
Closing, feel free to reopen if you feel like I haven't replied to all your questions/comments :)
